# Generated by Django 4.1.3 on 2022-11-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boundsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minlat', models.FloatField()),
                ('minlon', models.FloatField()),
                ('maxlat', models.FloatField()),
                ('maxlon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='copyrightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('licence', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='linkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField()),
                ('text', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mailType',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='trksegType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='wptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('ele', models.FloatField()),
                ('time', models.DateTimeField()),
                ('magvar', models.FloatField()),
                ('geoidheight', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('cmt', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
                ('sym', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('fix', models.CharField(max_length=200)),
                ('sat', models.PositiveIntegerField()),
                ('hdop', models.FloatField()),
                ('vdop', models.FloatField()),
                ('pdop', models.FloatField()),
                ('ageofdgpsdata', models.FloatField()),
                ('dgpsid', models.IntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype')),
            ],
        ),
        migrations.CreateModel(
            name='trkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cmt', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype')),
                ('trkseg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.trksegtype')),
            ],
        ),
        migrations.AddField(
            model_name='trksegtype',
            name='trkpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.wpttype'),
        ),
        migrations.CreateModel(
            name='rteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cmt', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype')),
                ('rtept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.wpttype')),
            ],
        ),
        migrations.CreateModel(
            name='personType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.mailtype')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype')),
            ],
        ),
        migrations.CreateModel(
            name='metadataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('keywords', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.persontype')),
                ('bounds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.boundstype')),
                ('copyright', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.copyrighttype')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype')),
            ],
        ),
        migrations.CreateModel(
            name='gpxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=200)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.metadatatype')),
                ('rte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.rtetype')),
                ('trk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.trktype')),
                ('wpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPXManager.wpttype')),
            ],
        ),
    ]
