# Generated by Django 4.1.3 on 2022-11-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPXManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundstype',
            name='maxlat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boundstype',
            name='maxlon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boundstype',
            name='minlat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boundstype',
            name='minlon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='copyrighttype',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='copyrighttype',
            name='licence',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='copyrighttype',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gpxtype',
            name='creator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtype',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.metadatatype'),
        ),
        migrations.AlterField(
            model_name='gpxtype',
            name='rte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.rtetype'),
        ),
        migrations.AlterField(
            model_name='gpxtype',
            name='trk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.trktype'),
        ),
        migrations.AlterField(
            model_name='gpxtype',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gpxtype',
            name='wpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.wpttype'),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='href',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linktype',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mailtype',
            name='domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.persontype'),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='bounds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.boundstype'),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='copyright',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.copyrighttype'),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype'),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.mailtype'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='cmt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype'),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='rtept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.wpttype'),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='src',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rtetype',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trksegtype',
            name='trkpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.wpttype'),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='cmt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype'),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='src',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='trkseg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.trksegtype'),
        ),
        migrations.AlterField(
            model_name='trktype',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='ageofdgpsdata',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='cmt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='dgpsid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='ele',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='fix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='geoidheight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='hdop',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype'),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='magvar',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='pdop',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='sat',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='src',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='sym',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='vdop',
            field=models.FloatField(null=True),
        ),
    ]
