# Generated by Django 4.1.3 on 2022-11-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPXManager', '0002_alter_boundstype_maxlat_alter_boundstype_maxlon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpttype',
            name='ageofdgpsdata',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='cmt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='dgpsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='ele',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='fix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='geoidheight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='hdop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPXManager.linktype'),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='magvar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='pdop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='sat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='src',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='sym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wpttype',
            name='vdop',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
